fix: Updating checkbox to match designs
ZebraDevs/zeta_flutter pull request #83
Opened 2024-05-29 14:33 UTC by mikecoomber

2024-05-30 13:34 UTC, ahmed-osman3 approved these changes

2024-06-03 13:45 UTC, thelukewalton requested changes

2024-06-03 13:45 UTC, thelukewalton commented on lib/src/components/checkbox/checkbox.dart
> +      enabled: !widget.disabled,
Styles for disabled do not seem to work

2024-06-04 09:42 UTC, thelukewalton approved these changes

2024-06-04 09:45 UTC, merged